ePub/ePub/Controllers/GuestViewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ePub;

namespace ePub.Controllers
{
    public class GuestViewController : Controller
    {
        private eLibraryEntities2 db = new eLibraryEntities2();

        // GET: GuestView
        public ActionResult Index()
        {
            var eBooks = db.eBooks.Include(e => e.User).Include(e => e.User1);
            return View(eBooks.ToList());
        }

        // GET: GuestView/Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eBook eBook = db.eBooks.Find(id);
            if (eBook == null)
            {
                return HttpNotFound();
            }
            return View(eBook);
        }

        // GET: GuestView/Preview
        public ActionResult Preview(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eBook eBook = db.eBooks.Find(id);
            if (eBook == null)
            {
                return HttpNotFound();
            }
            return View(eBook);
        }

        // GET: GuestView/Export
        public ActionResult Export(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eBook eBook = db.eBooks.Find(id);
            if (eBook == null)
            {
                return HttpNotFound();
            }
            return View(eBook);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ePub/ePub/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ePub.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AboutAndContact()
        {
 
            return View();
        }

       
    }
}

ePub/ePub/Views/Home/AboutAndContact.cshtml
@{
    ViewBag.Title = "E-Books";
}
<h2>Welcome to E - books App!</h2>

<p>
    This application allows users to create, edit and publish e-books.
</p>
<address>
    Unska 3<br />
    Hrvatska, ZG 10 000<br />
    Phone <br />
    01 0000 000
</address>
<address>
    <strong>Support:</strong>   <a href="ivica.boticki@fer.hr">ivica.boticki@fer.hr</a><br />
    <strong>Marketing:</strong> <a href="ivica.boticki@fer.hr">ivica.boticki@fer.hr</a>
</address>

ePub/ePub/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>E - BOOK APPLICATION</h1>
    <p class="lead">E-Book Application is a free web site for publishing and editing e - books.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>LOG IN</h2>
        <p>
            Already registered? Log in for more options!
        </p>
       @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
    </div>
    <div class="col-md-4">
        <h2>REGISTER</h2>
        <p>
            Not registered yet? In just a few minutes get all options that are not available to Guests.
        </p>
            @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
    </div>
    <div class="col-md-4">
        <h2>SIGN IN AS GUEST</h2>
        <p>
            Just wanna look around? Sign in as Guest. Guests have limited options.
        </p>
        @Html.ActionLink("Sign in as Guest", "Index", "GuestView")
    </div>
</div>