ePub/ePub/Models/eBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ePub;

namespace ePub.Models
{
    public class eBooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: eBooks
        public ActionResult Index()
        {
            return View(db.eBooks.ToList());
        }

        // GET: eBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eBook eBook = db.eBooks.Find(id);
            if (eBook == null)
            {
                return HttpNotFound();
            }
            return View(eBook);
        }

        // GET: eBooks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: eBooks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "eBookId,Name,CreatorId,CreatedBy,CreationDate,ModifiedBy,ModificationDate")] eBook eBook)
        {
            if (ModelState.IsValid)
            {
                db.eBooks.Add(eBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eBook);
        }

        // GET: eBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eBook eBook = db.eBooks.Find(id);
            if (eBook == null)
            {
                return HttpNotFound();
            }
            return View(eBook);
        }

        // POST: eBooks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "eBookId,Name,CreatorId,CreatedBy,CreationDate,ModifiedBy,ModificationDate")] eBook eBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eBook);
        }

        // GET: eBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            eBook eBook = db.eBooks.Find(id);
            if (eBook == null)
            {
                return HttpNotFound();
            }
            return View(eBook);
        }

        // POST: eBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            eBook eBook = db.eBooks.Find(id);
            db.eBooks.Remove(eBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ePub/ePub/Controllers/ChaptersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ePub;
using System.IO;
using System.Text;

namespace ePub.Controllers
{
    public class ChaptersController : Controller
    {
        private eLibraryEntities2 db = new eLibraryEntities2();

        // GET: Chapters
        public ActionResult Index(int? bookId)
        {
            if (bookId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var chapters = db.Chapters.Where(c => c.eBookId == bookId).Include(c => c.eBook).Include(c => c.User).Include(c => c.User1);
            ViewBag.eBookId = bookId;
            ViewBag.eBookName = db.eBooks.Find(bookId).Name;
            return View(chapters.ToList());
        }

        // GET: Chapters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chapter chapter = db.Chapters.Find(id);
            if (chapter == null)
            {
                return HttpNotFound();
            }
            ViewBag.id = db.Chapters.Find(id).eBookId;
            return View(chapter);
        }

        // GET: Chapters/Create
        public ActionResult Create(int bookId)
        {
            int newChapterId;
            if (db.Chapters.Where(c => c.eBookId == bookId).Any())
            {
                newChapterId = db.Chapters.Where(c => c.eBookId == bookId).Max(c => c.ChapterNumber) + 1;
            }
            else
            {
                newChapterId = 1;
            }
            ViewBag.BookId = bookId;
            ViewBag.ChapterNumber = newChapterId;
            return View();
        }

        
        // POST: Chapters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]

        public ActionResult Create(int bookId, [Bind(Include = "html,ChapterNumber")] Chapter chapter)
        {
            //Kako provjeriti je li prazno? tj. kako napraviti da se pojavi "required" error message?
            if (chapter != null && chapter.html == null)
            {
                chapter.html = " ";
            }
            List<int> allChapters = db.Chapters.Where(c => c.eBookId == bookId).Select(c => c.ChapterNumber).ToList();
            if (allChapters.Contains(chapter.ChapterNumber))
            {
                ModelState.AddModelError("", "Chapter already exists!");
            }
            
            
            //zasad user = bilo koji prvi, kasnije to promijeniti
            chapter.CreatedBy = db.Users.First().UserId;
            chapter.ModifiedBy = chapter.CreatedBy;
            chapter.CreationDate = DateTime.Now;
            chapter.ModificationDate = DateTime.Now;
            chapter.eBookId = bookId;

            if (ModelState.IsValid)
            {
                db.Chapters.Add(chapter);
                db.SaveChanges();
                return RedirectToAction("Index", new { bookId = bookId});
            }

            return View(chapter);
        }

        // GET: Chapters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chapter chapter = db.Chapters.Find(id);
            if (chapter == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.content = chapter.html;
            ViewBag.id = chapter.eBookId;
            ViewBag.ChapterNumber = chapter.ChapterNumber;
            ViewBag.ebookName = chapter.eBook.Name;
            return View(chapter);
        }

        // POST: Chapters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ChapterId,ChapterNumber,ebook,ebookId,html,CreatedBy,ModifiedBy,CreationDate,User,User1")] Chapter chapter)
        {
            List<int> allChapters = db.Chapters.Where(c => c.eBookId == chapter.eBookId 
                                                     && c.ChapterId != chapter.ChapterId ).Select(c => c.ChapterNumber).ToList();
            allChapters.Remove(chapter.ChapterId);
            if (allChapters.Contains(chapter.ChapterNumber))
            {
                ModelState.AddModelError("", "Chapter already exists!");
            }
            if (chapter != null && chapter.html == null)
            {
                chapter.html = " ";
            }
            chapter.ModificationDate = DateTime.Now;
            //Promijeniti u User na kraju
            chapter.ModifiedBy = db.Users.First().UserId;
            if (ModelState.IsValid)
            {
                db.Entry(chapter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { bookId = chapter.eBookId});
            }
            
            return View(chapter);
        }

        // GET: Chapters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chapter chapter = db.Chapters.Find(id);
            if (chapter == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookId = chapter.eBookId;
            return View(chapter);
        }

        // POST: Chapters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Chapter chapter = db.Chapters.Find(id);
            int tempId = chapter.eBookId;
            db.Chapters.Remove(chapter);
            db.SaveChanges();
            return RedirectToAction("Index", new { bookId = tempId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ePub/ePub/Views/Chapters/Create.cshtml
@model ePub.Chapter

@{
    ViewBag.Title = "Create new chapter";
}



<head>
    <script type="text/javascript" src="@Url.Content("~/ckeditor/ckeditor.js")"></script>
    <script type="text/javascript" src="@Url.Content("/ckeditor/adapters/jquery.js")"></script>
</head>
<body>
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <p>
                <h2>Chapter @ViewBag.ChapterNumber </h2>
            </p>
            <div class="form-group">
                @Html.LabelFor(model => model.ChapterNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChapterNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChapterNumber, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-md-10">
                @Html.TextAreaFor(model => model.html, new { @class = "ckeditor", @id = "editor1" })
                @Html.ValidationMessageFor(model => model.html, "", new { @class = "text-danger" })
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn pull-right" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index", "Chapters", new { bookId = ViewBag.BookId }, null)
    </div>
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script language="javascript" type="text/javascript"> 
        jQuery(".ckeditor").ckeditor();
    </script>
}

ePub/ePub/Views/Chapters/Delete.cshtml
@model ePub.Chapter

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this chapter?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Chapter Number:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChapterNumber)
        </dd>

        <dt>
            Created:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Username)
        </dd>

        <dt>

        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            Last Modified:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User1.Username)
        </dd>

        <dt>

        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModificationDate)
        </dd>

        <dt>
            E-book:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eBook.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Cancel", "Index", "Chapters", new { bookId = ViewBag.BookId }, null)
        </div>
    }
</div>

ePub/ePub/Views/Chapters/Details.cshtml
@model ePub.Chapter

@{
    ViewBag.Title = "Details";
}


<h2>Details</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Chapter Number:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChapterNumber)
        </dd>

        <dt>
            Created:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Username)
        </dd>

        <dt>
            
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            Last Modified:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User1.Username)
        </dd>

        <dt>
            
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModificationDate)
        </dd>

        <dt>
            E-book:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eBook.Name)
        </dd>


        

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ChapterId }) |
    @Html.ActionLink("Back to Chapter List", "Index", "Chapters", new { bookId = ViewBag.id }, null)
</p>

ePub/ePub/Views/Chapters/Edit.cshtml
@model ePub.Chapter

@{
    ViewBag.Title = "Edit";
}

<head>
    <script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
</head>

<h2>Edit Chapter</h2>

<div>
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <h3><b>@ViewBag.ebookName</b></h3>
            <h4>Chapter @ViewBag.ChapterNumber </h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ChapterId)
            @Html.HiddenFor(model => model.eBookId)
            @Html.HiddenFor(model => model.CreatedBy)
            @Html.HiddenFor(model => model.CreationDate)
            

            <div class="form-group">
                @Html.LabelFor(model => model.ChapterNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChapterNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChapterNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-10">
                @Html.TextAreaFor(model => model.html, new { @class = "ckeditor", @id = "editor1" })
                @Html.ValidationMessageFor(model => model.html)
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn pull-right" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("Back to Chapters", "Index", "Chapters", new { bookId = ViewBag.id }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ePub/ePub/Views/Chapters/Index.cshtml
@model IEnumerable<ePub.Chapter>

@{
    ViewBag.Title = "Index";
}

<h2><b>@ViewBag.eBookName</b></h2>

<p>

    @Html.ActionLink("Create New Chapter", "Create", new { bookId = ViewBag.ebookId }, null)
</p>
<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            Content preview (html)
        </th>
        <th>
            Created 
        </th>
        <th>
           
        </th>
        <th>
            Last modified
        </th>
        <th>
            
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ChapterNumber)
            </td>
            <td>
                @if(item.html.Length > 43)
                {
                    var contentBeginning = item.html.Substring(0, 40) + "...";
                    @contentBeginning
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.html)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModificationDate)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.User1.Username)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ChapterId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ChapterId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ChapterId })
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Back to eBooks", "Index", "eBooks")